type Query {
  libraries(limit: Int, offset: Int): [Library!]!
  libraryByID(libraryID: ID!): Library!
  libraryByUserAndName(userID: ID!, name: String!): Library!
  librariesByUserID(userID: ID!, limit: Int, offset: Int): [Library!]!
}

type Mutation {
  renameLibrary(libraryID: ID!, name: String!): Library!
  addMovieToLibrary(libraryID: ID!, movieID: String!): Library!
  removeMovieFromLibrary(libraryID: ID!, movieID: String!): Library!
}

type Library {
  libraryID: ID!
  userID: ID!
  name: String!
  movies: [String!]!
}
