type Query {
  movies(
    limit: Int
    offset: Int
    searchBy: String
    filter: MovieFilter
  ): [Movie!]!
  movie(imdbID: ID!): Movie!
}

input MovieFilter {
  isAdult: Boolean
  runtimeMinutesRange: MinutesRange
  averageRatingRange: RatingRange
  releaseYearRange: YearRange
  totalVotesRange: VotesRange
  genres: [String!]
}

input VotesRange {
  min: Int
  max: Int
}

input YearRange {
  min: Int
  max: Int
}

input RatingRange {
  min: Float
  max: Float
}

input MinutesRange {
  min: Int
  max: Int
}

type Movie {
  imdbID: ID!
  primaryTitle: String!
  originalTitle: String!
  isAdult: Boolean!
  startYear: Int!
  runtimeMinutes: Int!
  averageRating: Float!
  totalVotes: Int!
  poster: String
  genres: [String!]!
}
