type Query {
  movies(
    limit: Int
    offset: Int
    searchBy: SearchOptions
    filter: MovieFilter
  ): [Movie!]!
  movie(imdbID: ID!): Movie!
}

input SearchOptions {
  imdbID: ID
  primaryTitle: String
  originalTitle: String
}

input MovieFilter {
  isAdult: Boolean
  runtimeMinutesRange: MinutesRange
  averageRating: RatingRange
  totalVotes: Int
  genres: [String!]
}

input RatingRange {
  min: Float
  max: Float
}

input MinutesRange {
  min: Int
  max: Int
}

type Movie {
  imdbID: ID!
  primaryTitle: String!
  originalTitle: String!
  isAdult: Boolean!
  startYear: Int!
  runtimeMinutes: Int!
  averageRating: Float!
  totalVotes: Int!
  poster: String
  genres: [String!]!
}
